In [1]:
import pandas as pd
import sqlite3
import csv
import prettytable
prettytable.DEFAULT = 'DEFAULT'
%load_ext sql
%sql sqlite:///final.db
conn = sqlite3.connect("final.db")
cursor = conn.cursor()

In [9]:
df = pd.read_csv('chicagocrimedata.csv')
#df = pd.read_csv("chicagocrimedata.csv")
df.to_sql("chicago_crime_data", conn, if_exists='replace', index=False,method="multi")

533

In [19]:
df = pd.read_csv("chicagopublicschools.csv")
df.to_sql("chicago_public_schools" , conn , if_exists = 'replace' , index = False)

566

In [16]:
df1 = pd.read_csv('chicagocensusdata.csv')
df1.to_sql("census_data" , conn , if_exists = 'replace' , index = False, method = "multi")

78

In [54]:
%sql select * from chicago_crime_data where primary_type = 'KIDNAPPING'  and description like '%child%' ;

 * sqlite:///final.db
Done.

[(5276766, 'HN144152', '2007-01-26', '050XX W VAN BUREN ST', '1792', 'KIDNAPPING', 'CHILD ABDUCTION/STRANGER', 'STREET', 0, 0, 1533, 15, 29.0, 25.0, '20', 1143050.0, 1897546.0, 2007, 41.87490841, -87.75024931, '(41.874908413, -87.750249307)')]

In [58]:
%sql select * from chicago_crime_data limit 5;

 * sqlite:///final.db
Done.

[(3512276, 'HK587712', '2004-08-28', '047XX S KEDZIE AVE', '890', 'THEFT', 'FROM BUILDING', 'SMALL RETAIL STORE', 0, 0, 911, 9, 14.0, 58.0, '6', 1155838.0, 1873050.0, 2004, 41.8074405, -87.70395585, '(41.8074405, -87.703955849)'),
 (3406613, 'HK456306', '2004-06-26', '009XX N CENTRAL PARK AVE', '820', 'THEFT', '$500 AND UNDER', 'OTHER', 0, 0, 1112, 11, 27.0, 23.0, '6', 1152206.0, 1906127.0, 2004, 41.89827996, -87.71640551, '(41.898279962, -87.716405505)'),
 (8002131, 'HT233595', '2011-04-04', '043XX S WABASH AVE', '820', 'THEFT', '$500 AND UNDER', 'NURSING HOME/RETIREMENT HOME', 0, 0, 221, 2, 3.0, 38.0, '6', 1177436.0, 1876313.0, 2011, 41.81593313, -87.62464213, '(41.815933131, -87.624642127)'),
 (7903289, 'HT133522', '2010-12-30', '083XX S KINGSTON AVE', '840', 'THEFT', 'FINANCIAL ID THEFT: OVER $300', 'RESIDENCE', 0, 0, 423, 4, 7.0, 46.0, '6', 1194622.0, 1850125.0, 2010, 41.74366532, -87.56246276, '(41.743665322, -87.562462756)'),
 (10402076, 'HZ138551', '2016-02-02', '033XX W 66TH ST', '820', 'THEFT', '$500 AND UNDER', 'ALLEY', 0, 0, 831, 8, 15.0, 66.0, '6', 1155240.0, 1860661.0, 2016, 41.7734553, -87.70648047, '(41.773455295, -87.706480471)')]

In [45]:
%sql select community_area_name from census_data limit 1;

 * sqlite:///final.db
Done.

[(1.0, 'Rogers Park', 7.7, 23.6, 8.7, 18.2, 27.5, 23939, 39.0)]

In [29]:
%%sql 
select community_area_number , community_area_name from census_data where per_capita_income < 11000;

 * sqlite:///final.db
Done.

[(26.0, 'West Garfield Park'),
 (30.0, 'South Lawndale'),
 (37.0, 'Fuller Park'),
 (54.0, 'Riverdale')]

In [46]:
%%sql select * from census_data
order by percent_households_below_poverty desc limit 5;

 * sqlite:///final.db
Done.

[(54.0, 'Riverdale', 5.8, 56.5, 34.6, 27.5, 51.5, 8201, 98.0),
 (37.0, 'Fuller Park', 3.2, 51.2, 33.9, 26.6, 44.9, 10432, 97.0),
 (68.0, 'Englewood', 3.8, 46.6, 28.0, 28.5, 42.5, 11888, 94.0),
 (29.0, 'North Lawndale', 7.4, 43.1, 21.2, 27.6, 42.7, 12034, 87.0),
 (27.0, 'East Garfield Park', 8.2, 42.4, 19.6, 21.3, 43.2, 12961, 83.0)]

In [55]:
%sql select avg(safety_score) from chicago_public_schools;

 * sqlite:///final.db
Done.

[(49.50487329434698,)]

In [62]:
df = pd.read_csv("chicagocensusdata.csv")
df.describe()

,COMMUNITY_AREA_NUMBER,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX
count,77.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,77.000000
mean,39.000000,4.920513,21.739744,15.341026,20.330769,35.717949,25597.000000,49.506494
std,22.371857,3.658981,11.457231,7.499497,11.746514,7.284421,15196.405541,28.690556
min,1.000000,0.300000,3.300000,4.700000,2.500000,13.500000,8201.000000,1.000000
25%,20.000000,2.325000,13.350000,9.200000,12.075000,32.150000,15804.750000,25.000000
50%,39.000000,3.850000,19.050000,13.850000,18.650000,38.050000,21668.500000,50.000000
75%,58.000000,6.800000,29.150000,20.000000,26.600000,40.500000,28715.750000,74.000000
max,77.000000,15.800000,56.500000,35.900000,54.800000,51.500000,88669.000000,98.000000

In [65]:
df = pd.read_csv("Chicagocrimedata.csv")
df.describe()

,ID,BEAT,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE
count,5.330000e+02,533.000000,533.000000,490.000000,490.000000,5.290000e+02,5.290000e+02,533.00000,529.000000,529.000000
mean,6.228301e+06,1187.037523,11.195122,22.608163,37.542857,1.162876e+06,1.886223e+06,2008.34334,41.843429,-87.677818
std,3.027454e+06,660.592263,6.496631,13.080119,21.409514,1.650197e+04,3.009980e+04,4.94940,0.082798,0.060073
min,2.114900e+04,111.000000,1.000000,1.000000,1.000000,1.100658e+06,1.814512e+06,2001.00000,41.645796,-87.905227
25%,3.420516e+06,711.000000,6.000000,12.000000,23.000000,1.151715e+06,1.860454e+06,2004.00000,41.772556,-87.718166
50%,6.231712e+06,1111.000000,10.000000,24.000000,30.000000,1.163235e+06,1.891447e+06,2008.00000,41.857737,-87.676733
75%,8.875058e+06,1634.000000,16.000000,32.000000,58.000000,1.174618e+06,1.907711e+06,2012.00000,41.902298,-87.634677
max,1.127717e+07,2535.000000,25.000000,50.000000,77.000000,1.204126e+06,1.951001e+06,2018.00000,42.021178,-87.528223